### ISSUE TITLE
abstract for WES

### ISSUE THREAD

**Issue by thin-lizard** [WeberLab-UW/LS-phd#45]
possible venue for the [platform organizing typology](https://docs.google.com/document/d/1z6jbopQCUqCOrbLgztnZzIjWUGBnq0fv7wC7hA8JjzM/edit?pli=1) / gig worker center paper: https://www.britsoc.co.uk/media/26353/wes_si_cfp_dl310124.pdf

@lindseysschwartz - send prospective abstract to editors:  "is this what you're looking for"

**Comment by thin-lizard** [comment]
@nniiicc 

Here is the prospective abstract and email to the editors of this special issue: https://docs.google.com/document/d/1pnCIkb0t43cn0T2XaJvQEi5xfA6O2stmSQytB4Dgdfo/edit 

Main points for feedback:
- Q: Should we include the "three major contributions" section with the prospective abstract? 
- Conciseness and clarity for the abstract, as always. 
- Any necessary edits for the email 

lmk if you have any Qs, and TY!

**Comment by nniiicc** [comment]
@lindseysschwartz - lets add this to the agenda to talk about tomorrow. 
For this paper, I think we should consider the chapter 'Organizing the Unorganized' that discusses 'patterns of organzing' in a comaprative context (they are comparing national efforts at unionization) -> https://books.google.com/books?id=sV4TDAAAQBAJ&lpg=PA45&ots=AEN3okofad&dq=Organizing%20the%20Unorganized&lr&pg=PA50#v=onepage&q=Organizing%20the%20Unorganized&f=false (see in particular the table 4.1) - This is how we might empirically compare across examples of organizing gig workers

**Comment by thin-lizard** [comment]
I found another example in my reading notes - **Table 4.9** from this book: https://lostrabajadoresenargentina.files.wordpress.com/2013/09/kelly-1998-entero.pdf
<img width="533" alt="Screenshot 2023-11-15 at 10 36 54 AM" src="https://github.com/PugetSoundClinic-PIT/LS-phd/assets/75044820/f17d8485-169b-4a29-b788-17ba7bb3e98b">

**Comment by thin-lizard** [comment]
https://docs.google.com/document/d/1S2uLl0MQil4JmJNUf5cHfWbws3qzBqs2ogKvlgnqS3E/edit
